{
 "title": "Catalog Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "catalog", "label": "catalog", "query": { "query": "label_values(catalog)" } }
  ]
 },
 "panels": [
  {
   "title": "Number of Packages",
   "type": "stat",
   "description": "Packages / Catalog",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (catalog, package) (catalog_bundle_total{catalog=\"$catalog\"})) by (catalog)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Bundles",
   "type": "stat",
   "description": "Number of Bundles per Catalog",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (catalog) (catalog_bundle_total{catalog=\"$catalog\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Install Mode",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (catalog, package) (bundle_all_namespaces_support_total{catalog=\"$catalog\"})) by (catalog)",
     "legendFormat": "AllNamespaces"
    },
    {
     "expr": "count(count by (catalog, package) (bundle_single_namespace_support_total{catalog=\"$catalog\"})) by (catalog)",
     "legendFormat": "SingleNamespace"
    },
    {
     "expr": "count(count by (catalog, package) (bundle_own_namespace_support_total{catalog=\"$catalog\"})) by (catalog)",
     "legendFormat": "OwnNamespace"
    },
    {
     "expr": "count(count by (catalog, package) (bundle_multi_namespace_support_total{catalog=\"$catalog\"})) by (catalog)",
     "legendFormat": "MultiNamespace"
    },
    {
     "expr": "count(count by (catalog, package) (bundle_no_all_namespaces_support_total{catalog=\"$catalog\"})) by (catalog)",
     "legendFormat": "No AllNamespaces"
    },
    {
     "expr": "count(count by (catalog, package) (catalog_bundle_total{catalog=\"$catalog\"})) by (catalog)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "V1 Support Metrics",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (catalog, package) (bundle_has_validating_webhooks_total{catalog=\"$catalog\"} == 1 or bundle_has_mutating_webhooks_total{catalog=\"$catalog\"} or bundle_has_conversion_webhooks_total{catalog=\"$catalog\"})) by (catalog)",
     "legendFormat": "Webhooks"
    },
    {
     "expr": "count(count by (catalog, package) (bundle_has_v0_operator_condition_rbac_total{catalog=\"$catalog\"} == 1)) by (catalog)",
     "legendFormat": "OperatorCondition RBAC"
    },
    {
     "expr": "count(count by (catalog, package) (bundle_has_api_service_total{catalog=\"$catalog\"} == 1)) by (catalog)",
     "legendFormat": "APIServices"
    },
    {
     "expr": "count(count by (catalog, package) (bundle_no_all_namespaces_support_total{catalog=\"$catalog\"} == 1)) by (catalog)",
     "legendFormat": "No AllNamespaces"
    },
    {
     "expr": "count(count by (catalog, package) (bundle_has_package_required_total{catalog=\"$catalog\"} == 1 or bundle_has_gvk_required_property_total{catalog=\"$catalog\"} == 1)) by (catalog)",
     "legendFormat": "Dependencies"
    },
    {
     "expr": "count(count by (catalog, package) (bundle_supports_v1_total{catalog=\"$catalog\"} == 1)) by (catalog)",
     "legendFormat": "V1 Support"
    },
    {
     "expr": "count(count by (catalog, package) (bundle_supports_v1_techpreview_total{catalog=\"$catalog\"} == 1)) by (catalog)",
     "legendFormat": "v1 TP Support"
    }
   ]
  },
  {
   "title": "Packages with Dependencies",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (catalog) (\n  count by (catalog, package) (\n    bundle_has_gvk_required_property_total{catalog=\"$catalog\"} == 1\n  )\n)",
     "legendFormat": "GVK Required"
    },
    {
     "expr": "count by (catalog) (\n  count by (catalog, package) (\n    bundle_has_package_required_total{catalog=\"$catalog\"} == 1\n  )\n)",
     "legendFormat": "Package Required"
    },
    {
     "expr": "count by (catalog) (\n  count by (catalog, package) (\n    bundle_has_package_required_total{catalog=\"$catalog\"} == 1 or bundle_has_gvk_required_property_total{catalog=\"$catalog\"} == 1\n  )\n)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Feature Support",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "count by (catalog, __name__) (\n  sum by (catalog, package, __name__) (\n    bundle_supports_feature_disconnected_total{catalog=\"$catalog\"} == 1\n    or\n    bundle_supports_feature_fips_compliant_total{catalog=\"$catalog\"} == 1\n    or\n    bundle_supports_feature_proxy_aware_total{catalog=\"$catalog\"} == 1\n    or\n    bundle_supports_feature_tls_profiles_total{catalog=\"$catalog\"} == 1\n    or\n    bundle_supports_feature_token_auth_aws_total{catalog=\"$catalog\"} == 1\n    or\n    bundle_supports_feature_token_auth_azure_total{catalog=\"$catalog\"} == 1\n    or\n    bundle_supports_feature_token_auth_gcp_total{catalog=\"$catalog\"} == 1\n  )\n)",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Pacakges with API Services",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (catalog, __name__) (\n  sum by (catalog, package, __name__) (\n    bundle_has_api_service_total{catalog=\"$catalog\"} == 1\n  )\n) or (\n  0 * count by (catalog) (catalog_bundle_total{catalog=\"$catalog\"})\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Packages with Webhooks",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 10, "x": 2, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (catalog) (\n  count by (catalog, package) (\n    bundle_has_validating_webhooks_total{catalog=\"$catalog\"} == 1\n  )\n)",
     "legendFormat": "Validating"
    },
    {
     "expr": "count by (catalog) (\n  count by (catalog, package) (\n    bundle_has_mutating_webhooks_total{catalog=\"$catalog\"} == 1\n  )\n)",
     "legendFormat": "Mutating"
    },
    {
     "expr": "count by (catalog) (\n  count by (catalog, package) (\n    bundle_has_conversion_webhooks_total{catalog=\"$catalog\"} == 1\n  )\n)",
     "legendFormat": "Conversion"
    },
    {
     "expr": "count by (catalog) (\n  count by (catalog, package) (\n    bundle_has_validating_webhooks_total{catalog=\"$catalog\"} == 1\n    or\n    bundle_has_mutating_webhooks_total{catalog=\"$catalog\"} == 1\n    or\n    bundle_has_conversion_webhooks_total{catalog=\"$catalog\"} == 1\n  )\n)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Has v0 RBAC",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "count by (catalog, __name__) (\n  sum by (catalog, package, __name__) (\n    bundle_has_v0_operator_condition_rbac_total{catalog=\"$catalog\"} == 1\n    or\n    bundle_has_v0_subscription_rbac_total{catalog=\"$catalog\"} == 1\n  )\n)",
     "legendFormat": "{{__name__}}"
    }
   ]
  }
 ]
}