{
 "title": "Package",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "catalog", "label": "catalog", "query": { "query": "label_values(catalog)" } },
   {
    "name": "package",
    "label": "package",
    "query": {
     "query": "label_values({catalog=\"$catalog\"},package)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "# Bundles",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(catalog_bundle_total{catalog=\"$catalog\", package=\"$package\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "v1 support coverage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bundle_supports_v1_total{catalog=\"$catalog\", package=\"$package\"})/ sum(catalog_bundle_total{catalog=\"$catalog\", package=\"$package\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "v1 TP support coverage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bundle_supports_v1_techpreview_total{catalog=\"$catalog\", package=\"$package\"}) / sum(catalog_bundle_total{catalog=\"$catalog\", package=\"$package\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bundles w/ Webhooks",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bundle_has_validating_webhooks_total{catalog=\"$catalog\", package=\"$package\"} or bundle_has_mutating_webhooks_total{catalog=\"$catalog\", package=\"$package\"} or bundle_has_conversion_webhooks_total{catalog=\"$catalog\", package=\"$package\"}) or (\n  0 * count by (catalog, package) (catalog_bundle_total{catalog=\"$catalog\", package=\"$package\"})\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Install Mode Support",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "catalog_bundle_total{catalog=\"$catalog\", package=\"$package\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "(bundle_all_namespaces_support_total{catalog=\"$catalog\", package=\"$package\"})",
     "legendFormat": "AllNamespaces"
    },
    {
     "expr": "bundle_single_namespace_support_total{catalog=\"$catalog\", package=\"$package\"}",
     "legendFormat": "SingleNamespace"
    },
    {
     "expr": "bundle_own_namespace_support_total{catalog=\"$catalog\", package=\"$package\"}",
     "legendFormat": "OwnNamespace"
    },
    {
     "expr": "bundle_multi_namespace_support_total{catalog=\"$catalog\", package=\"$package\"}",
     "legendFormat": "MultiNamespace"
    }
   ]
  },
  {
   "title": "Webhook Support",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "catalog_bundle_total{catalog=\"$catalog\", package=\"$package\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "bundle_has_validating_webhooks_total{catalog=\"$catalog\", package=\"$package\"} or (\n  0 * count by (catalog, package, bundle) (catalog_bundle_total{catalog=\"$catalog\", package=\"$package\"})\n)",
     "legendFormat": "SingleNamespace"
    },
    {
     "expr": "bundle_has_mutating_webhooks_total{catalog=\"$catalog\", package=\"$package\"} or (\n  0 * count by (catalog, package, bundle) (catalog_bundle_total{catalog=\"$catalog\", package=\"$package\"})\n)",
     "legendFormat": "OwnNamespace"
    },
    {
     "expr": "bundle_has_conversion_webhooks_total{catalog=\"$catalog\", package=\"$package\"} or (\n  0 * count by (catalog, package, bundle) (catalog_bundle_total{catalog=\"$catalog\", package=\"$package\"})\n)",
     "legendFormat": "MultiNamespace"
    }
   ]
  }
 ]
}